  import 'package:flutter/material.dart';
  final ThemeData lightTheme = ThemeData(
    fontFamily: 'Quicksand',
    primarySwatch: MaterialColor(4287954195,{50: Color(0xfff4ffe6), 100: Color(0xffe8ffcc), 200: Color(0xffd1fe9a), 300: Color(0xffbafe67), 400: Color(0xffa3fd35), 500: Color(0xff8cfd02), 600: Color(0xff70ca02), 700: Color(0xff549801), 800: Color(0xff386501), 900: Color(0xff1c3300)}),
    brightness: Brightness.light,
    primaryColor: Color( 0xff94fd13 ),
    primaryColorBrightness: Brightness.light,
    primaryColorLight: Color( 0xffe8ffcc ),
    primaryColorDark: Color( 0xff549801 ),
    accentColor: Color( 0xff8cfd02 ),
    accentColorBrightness: Brightness.light,
    canvasColor: Color( 0xfffafafa ),
    scaffoldBackgroundColor: Color( 0xfffafafa ),
    bottomAppBarColor: Color( 0xffffffff ),
    cardColor: Color( 0xffffffff ),
    dividerColor: Color( 0x1f000000 ),
    highlightColor: Color( 0x66bcbcbc ),
    splashColor: Color( 0x66c8c8c8 ),
    selectedRowColor: Color( 0xfff5f5f5 ),
    unselectedWidgetColor: Color( 0x8a000000 ),
    disabledColor: Color( 0x61000000 ),
    buttonColor: Color( 0xffe0e0e0 ),
    toggleableActiveColor: Color( 0xff70ca02 ),
    secondaryHeaderColor: Color( 0xfff4ffe6 ),
    backgroundColor: Color( 0xffd1fe9a ),
    dialogBackgroundColor: Color( 0xffffffff ),
    indicatorColor: Color( 0xff8cfd02 ),
    hintColor: Color( 0x8a000000 ),
    errorColor: Color( 0xffd32f2f ),
    elevatedButtonTheme: ElevatedButtonThemeData(
      style: ElevatedButton.styleFrom(
        primary: Color( 0xff8cfd02 ),
      ),
    ),
    textButtonTheme: TextButtonThemeData(
      style: ElevatedButton.styleFrom(
        onPrimary: Color( 0xff8cfd02 ),
      ),
    ),
    buttonTheme: ButtonThemeData(
      textTheme: ButtonTextTheme.normal,
      minWidth: 88.0,
      height: 36.0,
      padding: EdgeInsets.only(top:0.0,bottom:0.0,left:16.0, right:16.0),
      shape:     RoundedRectangleBorder(
      side: BorderSide(color: Color(0xff000000), width: 0.0, style: BorderStyle.none, ),
      borderRadius: BorderRadius.all(Radius.circular(2.0)),
    )
 ,
      alignedDropdown: false ,
      buttonColor: Color( 0xffe0e0e0 ),
      disabledColor: Color( 0x61000000 ),
      highlightColor: Color( 0x29000000 ),
      splashColor: Color( 0x1f000000 ),
      colorScheme: ColorScheme(
        primary: Color( 0xff94fd13 ),
        primaryVariant: Color( 0xff94fd13 ),
        secondary: Color( 0xff8cfd02 ),
        secondaryVariant: Color( 0xff549801 ),
        surface: Color( 0xffffffff ),
        background: Color( 0xffd1fe9a ),
        error: Color( 0xffd32f2f ),
        onPrimary: Color( 0xff000000 ),
        onSecondary: Color( 0xff000000 ),
        onSurface: Color( 0xff000000 ),
        onBackground: Color( 0xff000000 ),
        onError: Color( 0xffffffff ),
        brightness: Brightness.light,
      ),
    ),
    inputDecorationTheme:   InputDecorationTheme(
    labelStyle: TextStyle(
      color: Color( 0xdd000000 ),
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    helperStyle: TextStyle(
      color: Color( 0xdd000000 ),
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    hintStyle: TextStyle(
      color: Color( 0xdd000000 ),
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    errorStyle: TextStyle(
      color: Color( 0xdd000000 ),
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    errorMaxLines: null,
    floatingLabelBehavior: FloatingLabelBehavior.auto,
    isDense: false,
    contentPadding: EdgeInsets.symmetric(horizontal: 15, vertical: 18),
    isCollapsed : false,
    prefixStyle: TextStyle(
      color: Color( 0xdd000000 ),
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    suffixStyle: TextStyle(
      color: Color( 0xdd000000 ),
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    counterStyle: TextStyle(
      color: Color( 0xdd000000 ),
      fontSize: 16.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    filled: false,
    fillColor: Color( 0x00000000 ),
      errorBorder: OutlineInputBorder(
        borderSide: BorderSide(color: Color( 0xffd32f2f ), width: 2, style: BorderStyle.solid, ),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      focusedBorder: OutlineInputBorder(
        borderSide: BorderSide(color: Color( 0xff8cfd02 ), width: 2, style: BorderStyle.solid, ),
        borderRadius: BorderRadius.all(Radius.circular(10.0)),
      ),
      focusedErrorBorder: OutlineInputBorder(
        borderSide: BorderSide(color: Color( 0xffd32f2f ), width: 2, style: BorderStyle.solid, ),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      disabledBorder: OutlineInputBorder(
        borderSide: BorderSide(color: Color( 0xff000000 ), width: 2, style: BorderStyle.solid, ),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      enabledBorder: OutlineInputBorder(
        borderSide: BorderSide(color: Colors.transparent, width: 2, style: BorderStyle.solid, ),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
      border: OutlineInputBorder(
        borderSide: BorderSide(color: Color( 0xff000000 ), width: 2, style: BorderStyle.solid, ),
        borderRadius: BorderRadius.all(Radius.circular(4.0)),
      ),
    ),
    iconTheme: IconThemeData(
      color: Color( 0xdd000000 ),
      opacity: 1.0,
      size: 24.0,
    ),
    primaryIconTheme: IconThemeData(
      color: Color( 0xff000000 ),
      opacity: 1.0,
      size: 24.0,
    ),
    accentIconTheme: IconThemeData(
      color: Color( 0xff000000 ),
      opacity: 1.0,
      size: 24.0,
    ),
    sliderTheme: SliderThemeData(
      activeTrackColor: Color( 0xff94fd13 ),
      inactiveTrackColor: Color( 0x3d94fd13 ),
      disabledActiveTrackColor: Color( 0x52549801 ),
      disabledInactiveTrackColor: Color( 0x1f549801 ),
      activeTickMarkColor: Color( 0x8ae8ffcc ),
      inactiveTickMarkColor: Color( 0x8a94fd13 ),
      disabledActiveTickMarkColor: Color( 0x1fe8ffcc ),
      disabledInactiveTickMarkColor: Color( 0x1f549801 ),
      thumbColor: Color( 0xff94fd13 ),
      disabledThumbColor: Color( 0x52549801 ),
      thumbShape: RoundSliderThumbShape(),
      overlayColor: Color( 0x2994fd13 ),
      valueIndicatorColor: Color( 0xff94fd13 ),
      valueIndicatorShape: PaddleSliderValueIndicatorShape(),
      showValueIndicator: ShowValueIndicator.onlyForDiscrete,
      valueIndicatorTextStyle: TextStyle(
      color: Color( 0xdd000000 ),
      fontSize: 14.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
    ),
    tabBarTheme: TabBarTheme(
      indicatorSize: TabBarIndicatorSize.tab,
      labelColor: Color( 0xdd000000 ),
      unselectedLabelColor: Color( 0xb2000000 ),
    ),
    chipTheme: ChipThemeData(
      backgroundColor: Color( 0x1f000000 ),
      brightness: Brightness.light,
      deleteIconColor: Color( 0xde000000 ),
      disabledColor: Color( 0x0c000000 ),
      labelPadding: EdgeInsets.only(top:0.0,bottom:0.0,left:8.0, right:8.0),
      labelStyle: TextStyle(
      color: Color( 0xde000000 ),
      fontSize: 14.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
      padding: EdgeInsets.only(top:4.0,bottom:4.0,left:4.0, right:4.0),
      secondaryLabelStyle: TextStyle(
      color: Color( 0x3d000000 ),
      fontSize: 14.0,
      fontWeight: FontWeight.w400,
      fontStyle: FontStyle.normal,
    ),
      secondarySelectedColor: Color( 0x3d94fd13 ),
      selectedColor: Color( 0x3d000000 ),
      shape: StadiumBorder( side: BorderSide(color: Color(0xff000000), width: 0.0, style: BorderStyle.none, ) ),
    ),
    dialogTheme: DialogTheme(
      shape:     RoundedRectangleBorder(
      side: BorderSide(color: Color(0xff000000), width: 0.0, style: BorderStyle.none, ),
      borderRadius: BorderRadius.all(Radius.circular(0.0)),
    )

    ),
  );
